### ISSUE TITLE
collection mapping not working

### ISSUE THREAD

**Issue by MaartenS** [surech/halarious#18]
Hi,

I'm getting a the following exception when I try to map a collection to a member with the following annotations.

```
java.lang.ClassCastException: com.google.gson.JsonArray cannot be cast to com.google.gson.JsonObject
```

I initiate the member as an empty ArrayList as stated on the website.

```
@HalEmbedded
private List<UserResource> planning = new ArrayList<UserResource>();
```

Any idea on how to fix this?
regards,
Maarten

**Comment by surech** [comment]
I reactivated the ignored unit test `GsonSerializerTest`. This one is serializing `TestResource` with the following field:

``` java
    @HalEmbedded(name = "test")
    private List<TestResource> resources = new ArrayList<>();
```

which is working without the described problem.

Please keep in mind that you can only embed objects which implement the marker interface `HalResource`.

**Comment by surech** [comment]
I extended the unittest even more and was still not able to reproduce your problem. Can you please provide more informations about your exception (stack trace, code snipplets)?

**Comment by talentprince** [comment]
@surech Hi, I found an issue, you need to initialize the List first, or it will be crash because 
```
Collection collection = (Collection) HalReflectionHelper.getValue(field, result);
  if (collection == null) {
         throw new HalDeserializingException("Collection is null; no values can be added");
 }
```

Since HAL support only list and object, so do you think we can give it initial type like ArrayList? like gson will parse List to ImmuableList

Like

```
collection = new ArrayList<>();
HalReflectionHelper.setValue(result, field, collection);
```
