### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by jonasfa** [surech/halarious#4]
Even though easier, deploying to a self-hosted repository raises security concerns.
Eg: a self-hosted repository could be attacked and have its artifacts replaced/patched, or even hacked 3rd party artifacts added (gson, guava, etc).

**Comment by surech** [comment]
Finally, halarious is available over Maven Central!
https://oss.sonatype.org/#nexus-search;quick~halarious
http://search.maven.org/#browse|1992865210

```
<dependency>
  <groupId>ch.halarious</groupId>
  <artifactId>halarious-core</artifactId>
  <version>0.14</version>
</dependency>
```
